name: Handle Dispatch Events

on: repository_dispatch

jobs:
  check_event:
    name: Check event payload
    if: github.event.client_payload.action == 'check'

    runs-on: ubuntu-latest

    steps:
    - name: Check event payload
      shell: bash
      run: |
        echo "${{ toJSON(github.event) }}"
